### ISSUE TITLE
Docrep has GPL license

### ISSUE THREAD

**Issue by nbren12** [xgcm/xgcm#308]
Hey @rabernat. Our legal team was recently reviewing our dependency stack in preparation for us open sourcing some of our code and we noticed that `docrep` has as a [GPL license](https://github.com/Chilipp/docrep/blob/master/LICENSE). Since this is dynamically imported here:
https://github.com/xgcm/xgcm/blob/34a77de7894a30cb80abcdd9c20571dbe54988ad/xgcm/grid.py#L10
This implies that xgcm is really available under a GPL license rather than the claimed MIT license. 

Since this import seems rather minor, would it possible to remove this runtime dependency on docrep? Currently it's not really possible for us to use xgcm. I think it's still okay of the docs need GPL code to be built, as long as the sdist on PyPI doesn't include GPL-derived stuff.

As an aside, we joined in on similar issues with necdf4 and cftime (see e.g. https://github.com/Unidata/netcdf4-python/issues/1073).

**Comment by rabernat** [comment]
Hi Noah. I had not realized that docrep had a GPL license. thanks for bringing this to our attention. And sorry for the headache this is causing for your work.

> Since this import seems rather minor, would it possible to remove this runtime dependency on docrep?

Could you clarify what you're proposing? Docrep is not just used for building the docs; it also helps dynamically generate the docstring you see in your repl or notebook environment. We use it to avoid duplication of redundant docstrings between the Grid and Axis classes. If we move it, most of our our current docstrings will break.

To remove this dependency, I see a few options:
1. Just remove it and allow the docstrings to become incomplete / inaccurate.
2. Fix the docstrings manually, using copy & paste to replace what docrep is currently doing.
3. Replace docrep with another package that does something equivalent under a permissive license.

I'd be happy to accept a PR for either 2 or 3. 1 would not be so ideal...

**Comment by nbren12** [comment]
No worries!

> Docrep is not just used for building the docs; it also helps dynamically generate the docstring you see in your repl or notebook environment.

Oh. I see. I don't know anything about docrep. Maybe the authors would be willing to change the license?

**Comment by rabernat** [comment]
I know the maintainer. I'll ask.

**Comment by nbren12** [comment]
Despite the issue being addressed upstream. I think there may still be some license incompatibility issue with xgcm. 

Docrep is available with an MIT license (https://github.com/Chilipp/docrep/issues/22) only for versions >= 0.3.2, but xgcm cannot be installed with these new versions: https://github.com/xgcm/xgcm/blob/f2e1314b1468d46cc430af1d90878e6ff007f2d9/setup.py#L13.

**Comment by jbusecke** [comment]
Thanks for bringing this up. I vaguely remember we had some issues with newer versions. Let me unpin this and see what happens. Maybe the problem has been resolved since we implemented this.

**Comment by jbusecke** [comment]
Well that did not work. Would have been too lucky I guess. 

From what I can currently see, this might require some [refactoring](https://docrep.readthedocs.io/en/latest/#changed-in-0-3) on our side. I am not sure if I can find some time this week, but I will try.

**Comment by nbren12** [comment]
Thanks for looking into this @jbusecke!

**Comment by nbren12** [comment]
@jbusecke @rabernat Any plans to address this? This license situation is still not cured.

**Comment by jbusecke** [comment]
@nbren12, this issue should be fixed once #384 is merged. Should we release a bugfix version of this?

**Comment by TomNicholas** [comment]
> Should we release a bugfix version of this?

I think we might as well.

**Comment by jbusecke** [comment]
> (Is there a guide for how to release xgcm anywhere?)

https://xgcm.readthedocs.io/en/latest/contributor_guide.html#how-to-release-a-new-version-of-xgcm-for-maintainers-only
